[package]
name = "pgui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
gpui = { git = "https://github.com/zed-industries/zed.git" }
gpui-component = { git = "https://github.com/longbridge/gpui-component.git" }
rust-embed = "8.2.0"
